NiacomLanding/urls.py
from django.contrib import admin
from django.urls import path

from NiacomLanding.views import HomePage


app_name = 'portfolio'

######TODO: START DOCKER FOR DEV of project FIRST
#####TODO make the overall landing page for Portifolio
#######TODO connect relavant settings and routing to this location to basketballer. 
urlpatterns = [
    path('home/', HomePage.as_view(), name='home'), 
]

UI_Navigate/urls.py
from django.contrib import admin
from django.urls import path

from UI_Navigate.views import HomePage, Coming_Soon


#NEed load pictures fuction.

# https://basketballer-crud-demo-ardiy.ondigitalocean.app/home/


app_name = 'UI_nav'


urlpatterns = [
    path('', HomePage.as_view(), name='home'), 


    # path('coming_soon', Coming_Soon.as_view(), name='soon'),
]

baskets/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('UI_Navigate.urls')), 
    path('about/', include('NiacomLanding.urls')), 
    path('baskets/', include('players.urls')), 
    path('weather/', include('weather_fe.urls')),

]

players/urls.py
from django.urls import path
from .views import PlayersList, PlayersDetailView, PlayersUpdateView, player_api_list
from players import views


app_name="players"

urlpatterns = [
    path('', views.landingPage, name='home'), 
    path('search/search/', views.search, name='search'), 
    path('heat/', PlayersList.as_view(), name='p_list'), 
    path('heat/<pk>/',PlayersDetailView.as_view(), name="p_details"), 
    path('heat/update/<pk>/',PlayersUpdateView.as_view(), name="p_update"), 
    path('api/heat/',views.player_api_list), 
]

weather_fe/urls.py
from django.contrib import admin
from django.urls import path

from weather_fe.views import Weather



app_name = 'Weathered'


# BASE URL NEEDS WEATHER ADDED. 

#JS and staic needs associations. 


urlpatterns = [
    path('weather/', Weather.as_view(), name='wea_fe'),
]

NiacomLanding/models.py
from django.db import models

# Create your models here.

UI_Navigate/models.py
from django.db import models

# Create your models here.

players/models.py
from tabnanny import verbose
from django.db import models
from django.urls import  reverse


#https://medium.com/django-rest/django-model-relations-63709bccb72d
#https://docs.djangoproject.com/en/4.0/topics/db/examples/one_to_one/



#TODO V2: DB flat file 2013 MIAMI HEAT Starting 5 saved to remote DB, Local Test DB
class Players(models.Model):
    f_name = models.CharField(verbose_name='First Name', max_length = 50, default="Faux")
    l_name = models.CharField(verbose_name='Last Name', max_length=50, default="Doe")
    number = models.IntegerField(verbose_name='Jersey Number', default=0)
    #shoe = models.URLField()
    #picture = models.ImageField(verbose_name='Player Image', max_length=500, blank=True, null=True)#Images\Player_Images\no_image_available.jpg"

    class Meta:
        db_table = "Ballers"
        verbose_name_plural = "Players"
      

    def __str__(self):
        return f'{self.f_name} {self.l_name} {self.number}'

    def get_url(self):
        return reverse('players:p_details', args=[self.id])



class Points(models.Model):
    player = models.OneToOneField(Players, on_delete=models.CASCADE,  primary_key=True)
    num_games = models.IntegerField()
    tot_points = models.IntegerField( default=0) 
    ppg = models.FloatField(verbose_name='PPG', default=0)
    

    class Meta:
        db_table = "Hoops"
        verbose_name_plural = "Points"
        

    def __str__(self):
        return f'{self.player.f_name} {self.player.l_name} ppg: {self.ppg}'



#one to one because I only want the latest single tweet. New tweets will overwrite the old. per a predefined backend schedule.
#Intentionally not using available twitter API.
#only tweets text
class Tweety(models.Model):
    player = models.OneToOneField(Players, on_delete=models.CASCADE)
    twitter_handle = models.CharField(max_length=100)
    tweet_body = models.CharField(max_length=500)


    class Meta:
        verbose_name_plural = "Tweet"

    def __str__(self):
        return f'{self.player.f_name} {self.twitter_handle}'

players/forms.py
from django import forms
from .models import Points
from django.forms import ModelForm


class PointsUpdateForm(ModelForm):

    #customized form field name
    tot_points = forms.CharField(label='Season Total Points')
  
    class Meta:
        model = Points
        fields = ['tot_points','ppg']
        

NiacomLanding/views.py
from django.shortcuts import render
from django.views import View
# Create your views here.


class HomePage(View):

    def get(self, request):
        template = "business/about.html"
        return render(request, template_name=template)

UI_Navigate/views.py
from django.shortcuts import render
from django.views import View
# Create your views here.


class HomePage(View):

    def get(self, request):
        template = "FE_Nav/index.html"
        return render(request, template_name=template)



class Coming_Soon(View):

    def get(self, request):
        template = "FE_Nav/coming_soon.html"
        return render(request, template_name=template)

players/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import (ListView,
                                 DetailView, UpdateView,DeleteView)

from rest_framework.decorators import api_view
from rest_framework.response import Response

from players.Serializers import PlayersSerializer


from django.db.models import Q
from .models import Points, Players
from .forms import PointsUpdateForm



def landingPage(request):
    return render(request, "players/landing_page.html")

#List all players
class PlayersList(ListView):
    model = Points
    


#ad pk and routing. 
def tweets(request, pk):
    #get object tweet by pk
    #include display as tweet card inside points_detail.
    return render(request, "players/twitter_feed.html")

#detail view routed through click of player name in list view
##points updatable through form
#TODO: V3 points updatable by AJAX on players latest tweet
#points default at 0 when player created

######################HERE
# https://www.youtube.com/watch?time_continue=234&v=wXG11HcJtOw&feature=emb_title
#https://www.youtube.com/results?search_query=djagno+call+image+url
#  https://www.etutorialspoint.com/index.php/356-how-to-display-image-from-database-in-django
# i think i can do something like {static record.img}   ###in db save the image name as text. 
class PlayersDetailView(DetailView):
    model = Points

#####and template can filter through using opropriate oop. 

####If that doesnt work.....
#TODO: NOW add shoe table details to Player/points detail page using include feature and pk

#TODO: Add tweet real routing to to Player/points detail page using include feature and pk

#Update PPG and Total Points
class PlayersUpdateView(UpdateView):
    
    
    model = Points
    form_class = PointsUpdateForm
   

   #routes back to Players List. PlayersList(ListView)
    def get_success_url(self):
        return reverse('players:p_details', args=[int(self.object.player.id)])


def search(request):
    # https://linuxhint.com/build-a-basic-search-for-a-django/

    results = [] # capture and array. 

    if request.method == "GET": 
        query = request.GET.get('search')

        if query == '': #if queary is blank do this.
            query = 'None'  #passed through if statment in template

        #http://docs.djangoproject.com/en/1.1/ref/models/querysets/#icontains
        #patern DBclass.objects.filter(Q(dbclass_field_icontains=query) | Q(author_name__icontains=query) | Q(price__icontains=query) )
        # )

        #get_url method on db pointing back to "p_details"
        
        results = Players.objects.filter(Q(f_name__icontains=query) | Q(l_name__icontains=query))
    
    return render(request, 'players/search_results.html', {'query':query, 'results':results})




#TODO GET THIS APP ONLINE AWS
@api_view(['GET'])
def player_api_list(request):
    if request.method == "GET":
        players = Players.objects.all()
        serializer = PlayersSerializer(players, many=True) #True tells djano to batch many objects
        return Response(serializer.data)

weather_fe/views.py
from django.shortcuts import render
from django.views import View

# Create your views here.


class Weather(View):

    def get(self, request):
        template = "FE_Weather/index.html"
        return render(request, template_name=template)

UI_Navigate/templates/FE_Nav/coming_soon.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Coming Soon</title>
</head>
<body>
    

    <a href="{% url 'UI_nav:home' %}"><img style="height: 800px" src="{%static 'images/coming_soon.gif'%}" alt=""></a>
    
</body>
</html>

UI_Navigate/templates/FE_Nav/index.html
{%load static%}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Testing only -->
    <link rel="stylesheet" href="{% static 'css/cutesy.css'%}">


    <title>Annias 954-716-3752</title>
</head>
<body>    

<!-- LAST UI STEP CHANGE FOCUS AREA of backgournd robot image slightly right -->

<div class="intro_area">
<h1>Annias Scott III</h1>
<h2>Software Developer </h2>
<h4>Call: 954-716-3752</h4>
</div>
<div class="container">
    <div class="feature">
        <a href="{%url 'portfolio:home'%}">
        <h6>About Me</h6>
        <img src="{% static 'images/about_me.png' %}" alt="">
        </a>
    </div>

    <div class="feature">
        <a href="{% url 'players:home' %}">
        <h6>Basket Baller CRUD</h6>
        <img src="{% static 'images/baller_crud.png' %}"alt="">
        </a>
    </div>

    <div class="feature">
        <a href="{% url 'Weathered:wea_fe' %}">
        <h6>JavaScript API Consumption</h6>
        <img src="{% static 'images/api_eat.png' %}" alt="">
        </a>
    </div>

    <!-- Entry Point for Class Roster API, Starting as bare list wrapping in react UI -->

    <div class="feature">
        <a href="https://www.linkedin.com/pulse/sorting-cleaning-data-python-annias-scott-iii/">
        <h6> Data Science: Python & Excel</h6>
        <img src="{% static 'images/Ai_pict.png' %}" alt="">
        </a>  
    </div> 
</div> 
</body>
</html>

players/templates/players/ads.html
{%load static%}
  <div class="adblock" >
        <a href=""><img style="border: 3px solid black; height:25%;" src="{% static 'Images/Contest/Win_Cruise.jpg' %}" alt=""></a>
  
    </div>

players/templates/players/base.html
{% load static %}
<!-- Nba Logo -->
<link rel="stylesheet" href="{%static 'UI_Style.css'%}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


<!-- Search  Zip code api closest 3 NBA arenas-->
<nav class="mb-5 navbar">
<!-- SEARCH COMPONENT -->
{% include "players/search.html" %}
</nav>



<!-- APP INSERTION POINT -->

<body class="listen">
    
{% block content %}
{% endblock %}

</body>






<!-- Footer -->
<!-- Careers Page Links to my Hoover fade CSS Resume-->
<footer class="py-3 my-4">
{% include "players/footer.html" %}
</footer>

players/templates/players/footer.html
<!-- TODO: APply routing -->


    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="{%url 'portfolio:home'%}" class="nav-link px-2 text-muted">CONTACT-ANNIAS</a></li>
      <li class="nav-item"><a href="{%url 'players:home'%}" class="nav-link px-2 text-muted">Home</a></li>
      <li class="nav-item"><a href="{%url 'players:home'%}" class="nav-link px-2 text-muted">Scores</a></li>
      <li class="nav-item"><a href="{%url 'players:home'%}" class="nav-link px-2 text-muted">Store</a></li>

    </ul>
    <p class="text-center text-muted">© 2022 Niacom, Inc</p>

players/templates/players/landing_page.html
{% extends "players/base.html" %}

<div class="container listy">
{% block content %}
<!-- END -->
<!-- Javascript Carusel -->

<div class="text-center">
<img class="rounded img-fluid" src="https://cdn.nba.com/manage/2022/07/chris-paul-pass.jpg" alt="">
</div>
<!-- <img src= "https://cdn.nba.com/manage/2022/07/simons-nurkic-lillard-talk.jpg" alt="">
<img src="https://cdn.nba.com/manage/2022/05/jrue-holiday-block-game-5-iso.jpg" alt=""> -->




<!-- Enter to win ticket FE -->
<!-- Ajax ticket hidden number to backend -->



<!-- Email ticket number -->
<!-- (Third Party DB) Java script runs reads script and 
    selects a winner, Java emails the winner, Marks remote DB that winner selected. and Winner emailed END -->

<!-- ############################################################################################# -->
<!-- HEAT CHAMPIONSHIP BANNER -->
<h1>SHOWCASE Of The MONTH</h1>



<button><a href="{% url 'players:p_list'%}"">2013 Miami Heat</a></button>
        <!-- APP INSERTION POINT 2013 MIAMI HEAT LISTVIEW -->

<!-- ############################################################################################# -->

<!-- Scroll area--> 
<!-- https://www.stubhub.com/nba-tickets/ -->




<!-- Sidebar -->
<!-- Nike LEBRON SOUTH BEACH DB with Cookies:TBD -->
<!-- Wear Testers Review Youtube -->
<!-- Buy Now node react app -->



{% endblock %}
</div>

players/templates/players/points_detail.html
{% extends "players/base.html" %}
{% load static %}

{% block content %}

<!-- Regoranize layout -->

<div class="container listy">

    <img src="{%static 'Images/Player_Images/no_image_available.jpg' %}" alt="">
    
    <div>
    <ul>
    <li>{{ object.player.f_name }} {{ object.player.l_name }} </li>
    <li>#{{ object.player.number }} </li>
    </ul>

    <!-- TODO: V2 Add Picture field to db -->
    <!-- TODO: Test picture not found/default image -->
    <!-- TODO: V2 JS Fancy 3 random animations on hover -->
    </div>
    <ul>
    
      
        <li>
            <h4>PPG:<span>{{ object.ppg }}</span></h4>
        </li>
    <li>
        <h6>Career Point Total: {{ object.tot_points }}</h6>
    </li>
    </ul>

  
            <!--route to edit players points, player name not editable -->
            <a href="{% url 'players:p_list' %}">Players</a>
            <a href="{% url 'players:p_update' object.player.id %}"">Update Points</a>
           
    

   

<div>

</div>



<div class="float-end">
<!-- Latest Tweets  -->
    {% include "players/twitter_feed.html" %}
</div>
</div>

{% endblock %}

players/templates/players/points_form.html
{% extends "players/base.html" %}
<!-- TODO: what is this form?  -->






{% block content %}
<div class="listy">




<div class="container">
<ul>
<li>{{ object.player.f_name }} {{ object.player.l_name }} </li>
<li>#{{ object.player.number }} </li>
</ul>
<form method="post">




{% csrf_token %}
{{ form.as_p }}

<!-- try button value save -->
<button class="btn btn-primary" type="submit" >Update</button>
</form>
<div class="text-center">
<a href="{% url 'players:p_list' %}">View All</a>
</div>
</div>












</div>



{% endblock %}

players/templates/players/points_list.html
{% extends "players/base.html" %}

{% block content %}


<div class="container listy">

{% for player in object_list %}


<ul> 

    
    
    <li><a href="{% url 'players:p_details' player.player.id %}">{{ player.player.f_name }} {{ player.player.l_name }}</a></li>
    <li>#{{ player.player.number }} </li>


    

</ul>




{% endfor %}
</div>


{% endblock %} 

players/templates/players/scores.html
<!-- Recent Game Scores -->
<!-- Takes Stats for starting PG, TEam Opponent name from dropdown menu.  -->

<!-- V3 point gaurd last ten game compare and winner -->

players/templates/players/search.html
<!-- NOTE: imported to base as include statment -->
{% load static %}
<img style="width:10%" src="{%static 'Images/LOGOS/NBA_LOGO.webp' %}" alt="">
<form action="{%url 'players:search' %}" method="get">
    <input name="search" type="" id="" placeholder="The Question...">
    <!-- TODO: MAKE Stand alone view for search.  -->
    <!-- Search is a list view of User requested key word -->
    <!-- Point the user back to appropriate list view of asked for items.   -->
    <button type="submit">Search</button>   
</form>

<!-- May require a DB of all areanas and a compare against googed address: Make the DB as flat as possible -->

players/templates/players/search_results.html
{% extends "players/base.html" %}

<!-- List view of search results -->


{% block content %}

<div class= "listy">
<div class="container">
<h3>The Answer: </h3>
{% if query %}
    <h2>
    {% with results.count as total_results %}
    Found {{ total_results }} result{{ total_results|pluralize }}
    {% endwith %}

    </h2>

    {% for p in results %}
    <ul>
        <li>{{ p.f_name }} {{ p.l_name }} </li>
        <ul>
            <ul><li>
                <a href="{{p.get_url}}">Continue...</a>
            </li></ul>
        </ul>
    </ul>



{% empty %}  
<h3>No results found.</h3>
{% endfor %}

{% endif %}
</div>
<!-- TODO:V2 on hover darkening and blue box -->

<!-- AD injection point -->


</div>




{% endblock %}

players/templates/players/twitter_feed.html
<!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> -->

<!-- START LOOP -->
<!-- TODO: after layout test api or db call system. DB can be static -->


    <!-- <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">DWade</h5>
          <h6 class="card-subtitle mb-2 text-muted">@DwyaneWade
        </h6>
          <p class="card-text">Quick! Pre Order your copy of Shady Baby Feels for that special little troublemaker in your life! 

            Out in bookstores on August 23rd.</p>
          <a href="#" class="card-link">Card link</a>
          <a href="#" class="card-link">Another link</a>
        </div>
      </div>

 -->



<!-- End LOOP -->

weather_fe/templates/FE_Weather/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="staticfiles/style.css">
    <link rel="stylesheet" href="{%static 'css/style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/a65ab32e45.js" crossorigin="anonymous"></script>
   
    <title>Weather_API</title>
</head>

<body>
    <div class="fancy">

    <!-- HEADER ... Todo Fix darkness of the water-->
<header class="all_water">
    <h1><img  src="{%static 'images/water_logo.png' %}" alt=""></h1>
    <!-- <h1><img  src="wave_vid.gif" alt=""></h1> -->
</header>



 <!-- NAV -->
<nav>
    <ul>
        <li><a href="{%url 'UI_nav:home' %}">Home</a></li>
        <li><a href="{%url 'portfolio:home' %}">About</a></li>
    </ul>
</nav>

 <!-- Content area -->

<main>
     <!-- image changes based on wheather -->
    <img id="temp_desc" src="{%static 'images/sunny.png' %}" alt="">


    
     <!-- right side data inline-->

     <!-- entry point for interacting with API with FE JS-->

     <!-- TODO Js equivalaent to python f string -->
                        <div class="container">
                             <!-- This line is semi broken but ignoring it to get up into production.  -->
                            <div id="city_query0"  value="0"></div> 
                           





                        
            <div class="CityNameBanner">
                <h1 id="city_name">MIAMI</h1>
            </div>
        <div class="data_ui">

            <div class="value">

                <div class="text_box">
                    <ul>
                        <!-- override text color and size js red if over 89degrees-->
                        <li class="texty" id="temperature">NaN</li>
                        <li class="texty" id="Time">00:00:00</li>

                       
                        <li class="texty" id="Percip_percent"><h5>Current Percipitation:</h5>
                            <ul>
                            <li id="percip">NONE</li>
                            </ul>
                        </li>
                    </ul>
                     
                    
                
                </div>
                <!-- the image is occasionally actually an ad for fasion that matches weather-->
                <img class="righty_img" src="{%static 'images/sun_glasses.png' %}" alt="">
            </div>

        </div>
     </div>

</main>

<footer>

</footer>
</div>




<script src="{%static 'scripts/scripts.js' %}"></script>

</body>
</html>